### ISSUE TITLE
Add ability to specify VolumeSnapshotClass on SnapshotGroups

### ISSUE THREAD

**Issue by dosullivan** [FairwindsOps/gemini#4]
One of the changes from `snapshot.storage.k8s.io/v1alpha1` to `snapshots.storage.k8s.io/v1beta1` is the renaming of `snapshotClassName` to `volumeSnapshotClassName`. When running Photon in a cluster using the v1beta1 API, Photon is unable to successfully complete VolumeSnapshots because of this mismatch.

As-is, in a cluster with the v1beta1 API, the snapshot controller scans the resource, tries to find the `volumeSnapshotClassName`, and then errors out when it can't find it, leaving the VolumeSnapshot in an incomplete state. 

In addition to updating to using the latest API standards, we should likely add `volumeSnapshotClassName` to the spec on SnapshotGroups. Since volumeSnapshotClasses correspond with StorageClasses, it's easy to imagine scenarios in which multiple will coexist on a cluster. In such scenarios, the user will need to specify the volumeSnapshotClass to successfully use the correct StorageClass and CSI driver.

**Comment by WojciechKarpiel** [comment]
Hi!

Here's a way to specify VolumeSnaphotClass for benefit of future people visiting this issue:

```
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: testbkmongo3
spec:
  persistentVolumeClaim:
    claimName: mongo3-mongod-persistent-storage-claim-mongo3-mongod-0
  schedule:
    - every: "10 minutes"
      keep: 3
    - every: hour
      keep: 1
  template:
    spec:
      volumeSnapshotClassName: test-snapshot-class      
```

(you can find field names at source code https://github.com/FairwindsOps/gemini/blob/master/pkg/types/snapshotgroup/v1beta1/snapshotgroup.go)
