### ISSUE TITLE
volumeSnapshotClassName in SnapshotGroup not working

### ISSUE THREAD

**Issue by Rickvanderwaal** [FairwindsOps/gemini#59]
### What happened?

The Github URL in snapshotgroup.go is incorrect. 
This causes the following template with volumeSnapshotClassName not working.
```
apiVersion: gemini.fairwinds.com/v1beta1
kind: SnapshotGroup
metadata:
  name: my-backup
spec:
  persistentVolumeClaim:
    claimName: my-pvc
  schedule:
    - every: day
      keep: 14
  template:
    spec:
      volumeSnapshotClassName: my-custom-snapshot-class
```
See: https://github.com/FairwindsOps/gemini/blob/main/pkg/types/snapshotgroup/v1beta1/snapshotgroup.go

### What did you expect to happen?

I expect to define my own volumeSnapshotClassName as documented in the readme.

### How can we reproduce this?

Create a SnapshotGroup with custom volumeSnapshotClassName.

### Version

gemini chart version 1.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
